-- use SYSADMIN role\
USE ROLE SYSADMIN;

-- create warehouse and role
CREATE ROLE DBT_TRAIN_ROLE;

CREATE WAREHOUSE DBT_TRAIN_WH WITH
    WAREHOUSE_TYPE = STANDARD
    WAREHOUSE_SIZE = XSMALL
    -- auto suspend after 2min of inactivity
    AUTO_SUSPEND = 120;

-- create database and schema
CREATE DATABASE DBT_TRAIN_DB;
CREATE SCHEMA DBT_TRAIN_ANALYTICS;

-- grant USAGE privileges to DBT_TRAIN_ROLE 
GRANT USAGE ON WAREHOUSE DBT_TRAIN_WH TO ROLE DBT_TRAIN_ROLE;
GRANT USAGE ON DATABASE DBT_TRAIN_DB TO ROLE DBT_TRAIN_ROLE;
GRANT USAGE ON SCHEMA DBT_TRAIN_ANALYTICS TO ROLE DBT_TRAIN_ROLE;

-- grant CREATE SCHEMA privilege to DBT_TRAIN_ROLE
GRANT CREATE SCHEMA ON DATABASE DBT_TRAIN_DB TO ROLE DBT_TRAIN_ROLE;

-- grant CREATE TABLE and CREATE VIEW to DBT_TRAIN_ROLE
GRANT CREATE TABLE ON SCHEMA DBT_TRAIN_ANALYTICS TO ROLE DBT_TRAIN_ROLE;
GRANT CREATE VIEW ON SCHEMA DBT_TRAIN_ANALYTICS TO ROLE DBT_TRAIN_ROLE;
