-- create MASKING_ADMIN role
USE ROLE USERADMIN;
CREATE ROLE DBT_TRAIN_MASKING_ADMIN;

use role ACCOUNTADMIN;
GRANT CREATE MASKING POLICY on SCHEMA DBT_TRAIN_DB.DBT_TRAIN_JAFFLE_SHOP to ROLE DBT_TRAIN_MASKING_ADMIN;
GRANT APPLY MASKING POLICY on account to ROLE DBT_TRAIN_MASKING_ADMIN;

GRANT USAGE ON DATABASE DBT_TRAIN_DB TO ROLE DBT_TRAIN_MASKING_ADMIN;
GRANT USAGE ON SCHEMA DBT_TRAIN_DB.DBT_TRAIN_JAFFLE_SHOP TO ROLE DBT_TRAIN_MASKING_ADMIN;

-- create DBT_TRAIN_READER and DBT_TRAIN_ANALYST role 
USE ROLE useradmin;
CREATE ROLE DBT_TRAIN_READER;
CREATE ROLE DBT_TRAIN_ANALYST;

USE ROLE securityadmin;
GRANT USAGE ON WAREHOUSE DBT_TRAIN_WH TO ROLE DBT_TRAIN_READER;
GRANT USAGE ON DATABASE DBT_TRAIN_DB TO ROLE DBT_TRAIN_READER;
GRANT USAGE ON SCHEMA DBT_TRAIN_DB.DBT_TRAIN_JAFFLE_SHOP TO ROLE DBT_TRAIN_READER;
GRANT SELECT ON TABLE DBT_TRAIN_DB.DBT_TRAIN_JAFFLE_SHOP.RAW_CUSTOMERS TO ROLE DBT_TRAIN_READER;

GRANT USAGE ON WAREHOUSE DBT_TRAIN_WH TO ROLE DBT_TRAIN_ANALYST;
GRANT USAGE ON DATABASE DBT_TRAIN_DB TO ROLE DBT_TRAIN_ANALYST;
GRANT USAGE ON SCHEMA DBT_TRAIN_DB.DBT_TRAIN_JAFFLE_SHOP TO ROLE DBT_TRAIN_ANALYST;
GRANT SELECT ON TABLE DBT_TRAIN_DB.DBT_TRAIN_JAFFLE_SHOP.RAW_CUSTOMERS TO ROLE DBT_TRAIN_ANALYST;

-- grant MASKING_ADMIN, DBT_TRAIN_READER, DBT_TRAIN_ANALYST role to attendees
GRANT ROLE DBT_TRAIN_MASKING_ADMIN TO USER jsmith;
GRANT ROLE DBT_TRAIN_READER TO USER jsmith;
GRANT ROLE DBT_TRAIN_ANALYST TO USER jsmith;


-- Volunteer 2
SHOW GRANTS OF ROLE DBT_TRAIN_ROLE;
SHOW GRANTS TO ROLE DBT_TRAIN_ROLE;
SHOW GRANTS ON TABLE RAW_CUSTOMERS;

