-- volunteer 1 
-- create DBT_TRAIN_READER and DBT_TRAIN_ANALYST role 
USE ROLE useradmin;
CREATE ROLE DBT_TRAIN_READER;
CREATE ROLE DBT_TRAIN_ANALYST;

USE ROLE securityadmin;
GRANT USAGE ON WAREHOUSE DBT_TRAIN_WH TO ROLE DBT_TRAIN_READER;
GRANT USAGE ON DATABASE DBT_TRAIN_DB TO ROLE DBT_TRAIN_READER;
GRANT USAGE ON SCHEMA DBT_TRAIN_DB.DBT_TRAIN_JAFFLE_SHOP TO ROLE DBT_TRAIN_READER;
GRANT SELECT ON TABLE DBT_TRAIN_DB.DBT_TRAIN_JAFFLE_SHOP.RAW_CUSTOMERS TO ROLE DBT_TRAIN_READER;

GRANT USAGE ON WAREHOUSE DBT_TRAIN_WH TO ROLE DBT_TRAIN_ANALYST;
GRANT USAGE ON DATABASE DBT_TRAIN_DB TO ROLE DBT_TRAIN_ANALYST;
GRANT USAGE ON SCHEMA DBT_TRAIN_DB.DBT_TRAIN_JAFFLE_SHOP TO ROLE DBT_TRAIN_ANALYST;
GRANT SELECT ON TABLE DBT_TRAIN_DB.DBT_TRAIN_JAFFLE_SHOP.RAW_CUSTOMERS TO ROLE DBT_TRAIN_ANALYST;

-- grant MASKING_ADMIN, DBT_TRAIN_READER, DBT_TRAIN_ANALYST role to attendees
GRANT ROLE DBT_TRAIN_READER TO USER ESTHER_HO;
GRANT ROLE DBT_TRAIN_ANALYST TO USER ESTHER_HO;

GRANT ROLE DBT_TRAIN_READER TO USER JIAHAO_TAN;
GRANT ROLE DBT_TRAIN_ANALYST TO USER JIAHAO_TAN;

GRANT ROLE DBT_TRAIN_READER TO USER NICK_LEONG;
GRANT ROLE DBT_TRAIN_ANALYST TO USER NICK_LEONG;

GRANT ROLE DBT_TRAIN_READER TO USER PENG_CHENG;
GRANT ROLE DBT_TRAIN_ANALYST TO USER PENG_CHENG;

GRANT ROLE DBT_TRAIN_READER TO USER SAMUEL_WONG;
GRANT ROLE DBT_TRAIN_ANALYST TO USER SAMUEL_WONG;

GRANT ROLE DBT_TRAIN_READER TO USER SAMUEL_WONG;
GRANT ROLE DBT_TRAIN_ANALYST TO USER SAMUEL_WONG;

GRANT ROLE DBT_TRAIN_READER TO USER SRILAKSHMI_SUBRAMANIAM;
GRANT ROLE DBT_TRAIN_ANALYST TO USER SRILAKSHMI_SUBRAMANIAM;

-- Volunteer 2
SHOW GRANTS OF ROLE DBT_TRAIN_ROLE;
SHOW GRANTS TO ROLE DBT_TRAIN_ROLE;
SHOW GRANTS ON TABLE RAW_CUSTOMERS;

